version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - dependencies
  ignore:
  - dependency-name: contentful
    versions:
    - 8.3.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.23.0
    - 7.24.0
  - dependency-name: gsap
    versions:
    - 3.6.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.8.0
  - dependency-name: imports-loader
    versions:
    - 2.0.0
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  - dependency-name: vue-notion
    versions:
    - 0.4.0
  - dependency-name: nuxt
    versions:
    - 2.15.0
    - 2.15.1
